algo_params:
  batch_size: 256
  buffer_size: 300000
  ent_coef: auto
  gamma: 0.98
  gradient_steps: 64
  learning_rate: 0.00073
  log_std_init: -3
  net_arch:
  - 64
  - 64
  tau: 0.02
  train_freq: 64
  use_sde: true
awet_params:
  AA_mode: true
  C_clip: 1.6
  C_e: 0.6
  C_l: 0.8
  ET_mode: true
  L_2: 0.005
  gradient_steps: 1000
  num_demos: 100
general_params:
  agent: AWET_SAC
  env_name: CustomPusherDense-v1
  exp_name: Algo_Exp
  expert_data_path: demos_data/pusher/Pusher_Dense_Demos_100.pkl
  num_episodes: 2000
  num_runs: 10
plotter_params:
  dpi: 70
  font_scale: 2.5
  height: 8
  linewidth: 3.5
  max_num_episodes: 2000
  smooth_window: 200
  width: 10
tester_params:
  num_episodes: 100
  render: false
